Improved code by making filter button in toolbar visible when aside filter component is hidden(#28u4w63)
hotwax/commerce-hub pull request #159
Opened 2022-04-26 11:49 UTC by azkyakhan

### Related Issues

Closes #

### Short Description and Why It's Useful
The filter menu button in the toolbar is visible when the aside filter component is hidden during scrolling.

### Screenshots of Visual Changes before/after (If There Are Any)
https://user-images.githubusercontent.com/82817616/165293338-54018683-08ed-401d-a222-1c17e98c09bb.mp4

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/hotwax/commerce-hub#contribution-guideline)

2022-04-28 07:04 UTC, adityasharma7 requested changes

2022-04-28 07:04 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +      filterButton: false,
Improve variable name

2022-04-28 07:04 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +    const el = document.querySelector('.order-filters') as Element;
Implement a method and call in mounted

2022-04-28 07:04 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +      if (entry.isIntersecting) {
```
this.filterButton = !entry.isIntersecting;
```

2022-04-28 08:42 UTC, azkyakhan commented on src/views/FindOrder.vue
> +      filterButton: false,
Ok Sir, I have renamed variable from `filterButton` to showFilterButton`.

2022-04-28 08:44 UTC, azkyakhan commented on src/views/FindOrder.vue
> +    const el = document.querySelector('.order-filters') as Element;
Ok sir I have created a method and called it in mounted.

2022-04-28 08:45 UTC, azkyakhan commented on src/views/FindOrder.vue
> +      if (entry.isIntersecting) {
I have done the suggested change.

2022-05-02 06:31 UTC, adityasharma7 approved these changes

2022-05-02 06:31 UTC, merged