Implemented: Code to check if user has permission to access the app(#2hr41aq)
hotwax/commerce-hub pull request #171
Opened 2022-08-22 12:38 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/commerce-hub#contribution-guideline)

2022-08-22 13:29 UTC, ymaheshwari1 requested changes

2022-08-22 13:29 UTC, ymaheshwari1 commented on src/services/UserService.ts
> +import api, {client} from '../api'
```suggestion
import api, {client} from '@/api'
```

2022-08-22 13:32 UTC, shashwatbangar commented on src/services/UserService.ts
> +import api, {client} from '../api'
Done sir.

2022-08-25 09:28 UTC, adityasharma7 approved these changes

2022-08-25 09:32 UTC, adityasharma7 approved these changes

2022-08-25 09:32 UTC, merged