Implemented: support of oms package for stock module
hotwax/commerce-hub pull request #183
Opened 2023-01-17 10:08 UTC by ymaheshwari1

### Related Issues

Closes #181 

### Short Description and Why It's Useful

- Installed latest version of oms package
- Used the oms methods for fetching product stock information
- Used Stock type from oms package

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/commerce-hub#contribution-guideline)

2023-01-18 07:32 UTC, adityasharma7 requested changes

2023-01-18 07:32 UTC, adityasharma7 commented on src/store/modules/stock/actions.ts
> +      const resp = await Promise.allSettled(products.map((product: any) => fetchProductsStockAtFacility([product.productId], product.facilityId)))
Improve variable name `resp`. We are storing list of responses

2023-01-18 07:32 UTC, adityasharma7 commented on src/store/modules/stock/actions.ts
> +        if (responseStatus === 'fulfilled') {
We should filter failed responses and log it

2023-08-31 13:11 UTC, Dhiraj1405 commented
Not priority for now. Hence, closing this pull request.

2023-08-31 13:11 UTC, closed without merging