Implemented Static UI for Find Order page
hotwax/commerce-hub pull request #2
Opened 2021-12-07 13:07 UTC by Utkarshkaraiya

2021-12-14 10:34 UTC, ymaheshwari1 commented
Please add branch id after each commit message and PR title

2021-12-14 10:39 UTC, ymaheshwari1 requested changes

2021-12-14 10:39 UTC, ymaheshwari1 commented on src/views/Order.vue
> +    <div class="search">
Improve indentation

2021-12-14 10:39 UTC, ymaheshwari1 commented on src/views/Order.vue
> +             <ion-chip>
Improve indentation

2021-12-15 06:15 UTC, ymaheshwari1 requested changes

2021-12-15 06:15 UTC, ymaheshwari1 commented on src/locales/en.json
> +
Remove unwanted lines

2021-12-15 06:15 UTC, ymaheshwari1 commented on src/views/Order.vue
> +                >
Properly close the tags.

2021-12-15 06:20 UTC, Utkarshkaraiya commented on src/views/Order.vue
> +    <div class="search">
Done sir

2021-12-15 06:20 UTC, Utkarshkaraiya commented on src/views/Order.vue
> +             <ion-chip>
Done sir

2021-12-15 06:22 UTC, Utkarshkaraiya commented on src/locales/en.json
> +
Done sir

2021-12-15 06:22 UTC, Utkarshkaraiya commented on src/views/Order.vue
> +                >
Done sir

2021-12-15 06:32 UTC, ymaheshwari1 approved these changes
LGTM

2021-12-22 06:39 UTC, merged