Implemented functionality for find order page ( #1wn444v )
hotwax/commerce-hub pull request #25
Opened 2022-01-05 12:55 UTC by meet-aniket

This branch was deleted from my forked repo and I was not able to make changes in PR which were recommended by @ymaheshwari1 Sir so I am making a new pull request for this change and closing that pull request,

2022-01-24 20:47 UTC, bashu22tiwari commented on src/views/Orders.vue
> +    ...mapGetters({
Import mapGetters first.

2022-01-24 20:47 UTC, bashu22tiwari commented on src/views/Orders.vue
> +    const store = useStore();
Import store first.

2022-01-24 20:48 UTC, bashu22tiwari commented on src/views/Orders.vue
> +        showToast(this.$t('Copied', { text }));
Import showToast first.

2022-01-24 20:49 UTC, bashu22tiwari commented on src/views/Orders.vue
> +      await Clipboard.write({
Import Clipboard first.

import { Plugins } from '@capacitor/core';
const { Clipboard } = Plugins;

2022-01-24 20:51 UTC, bashu22tiwari commented on src/views/Orders.vue
> +    async getOrders(vSize?: any, vIndex?: any){
Please confirm if you have used <script lang="ts"> instead of <script> as you are also using typescript here.

2022-01-24 20:53 UTC, bashu22tiwari commented
@meet-aniket , As you have changed name of Order.vue to Orders.vue. Please check if you have also updated it in router.

2022-01-24 20:55 UTC, bashu22tiwari commented on src/views/Orders.vue
> +})
Remove the extra bracket.

2022-01-24 20:56 UTC, bashu22tiwari commented on src/store/modules/order/actions.ts
> +          items: orders.groups,
Improve indentation.

2022-01-24 21:36 UTC, bashu22tiwari commented on src/main.ts
> +  getOrderIdentificationId(identifications: any, id: string) {
If we have not used this utility anywhere, then why we are implementing it in this PR?

2022-01-24 21:36 UTC, bashu22tiwari commented on src/main.ts
> +  getCustomerLoyalty(orderNotes: any, cusotmerLoyaltyOptions: any) {
If we have not used this utility anywhere, then why we are implementing it in this PR?

2022-01-24 21:36 UTC, bashu22tiwari commented on src/main.ts
> +  getShippingFrom(orderRoles: any, shippingOption: any){
If we have not used this utility anywhere, then why we are implementing it in this PR?

2022-01-25 04:13 UTC, ymaheshwari1 requested changes

2022-01-25 04:13 UTC, ymaheshwari1 commented on .env.example
> +VUE_APP_BASE_URL=https://dev-hc.hotwax.io/api/
We won't push this base URL change, remove this base URL change.

2022-01-26 06:11 UTC, closed without merging