Improved code to make nav section on home page responsive (#1xxup28)
hotwax/commerce-hub pull request #37
Opened 2022-01-25 09:35 UTC by azkyakhan

2022-01-25 09:48 UTC, azkyakhan commented
Uploading Home.mp4…

2022-01-25 09:48 UTC, azkyakhan commented
https://user-images.githubusercontent.com/82817616/150952985-0e25d6e0-6c03-453c-ab14-716d5028f85d.mp4

2022-01-25 21:35 UTC, dt2patel requested changes
See comments

2022-01-25 21:35 UTC, dt2patel commented on src/views/Home.vue
> +ion-label[slot="end"] {
This css rule is not necessary, find out why you have to use it and what the actual problem is. We are putting ion labels in end slot all the time, and we haven't needed to do this before.

2022-01-25 21:35 UTC, dt2patel commented on src/views/Home.vue
> +    overflow-x: hidden;
why do you need to hide overflow in desktop? If you need to reset it why not unset?

2022-01-25 21:40 UTC, dt2patel commented
Additionally, while working on nav section: 

1. remove extra css from this page
2. Add spacing between the internal nav items.
  - on desktop it should add space between depending on parent height
  - on mobile there should be a fixed amount of margin top, about 24px

2022-01-27 06:40 UTC, azkyakhan commented on src/views/Home.vue
> +    overflow-x: hidden;
Done sir

2022-01-27 06:45 UTC, azkyakhan commented on src/views/Home.vue
> +ion-label[slot="end"] {
I found two things due to which it was happening, first reason was text-align property which was set `initial` and second reason was `flex: 1` was set on slotted label. Then I also went through issue that `Disha` shared in the thread, this issue is solved in 5.7.0 in which they removed flex: 1 property on end slotted label by using `not` selector. So as of now I have removed this styling.

2022-01-27 06:53 UTC, azkyakhan commented
> Additionally, while working on nav section:
> 
> 1. remove extra css from this page
> 2. Add spacing between the internal nav items.
> 
> * on desktop it should add space between depending on parent height
> * on mobile there should be a fixed amount of margin top, about 24px



> Additionally, while working on nav section:
> 
> 1. remove extra css from this page
> 2. Add spacing between the internal nav items.
> 
> * on desktop it should add space between depending on parent height
> * on mobile there should be a fixed amount of margin top, about 24px

1. I haven't added any extra css, I have just adjusted them according to desktop and mobile view.
2. In mobile view I have given a `margin-top` of 24px whereas in desktop view I have unset that margin and justified the content of internal nav evenly so that the spacing between any two adjacent alignment items, before the first alignment item, and after the last alignment item is the same

2022-01-27 18:34 UTC, dt2patel commented
For extra CSS, there is some written from targeting anchor tag. Please delete that.

2022-01-27 18:34 UTC, dt2patel commented on src/views/Home.vue
> +ion-label[slot="end"] {
Ok so this will be fixed when upgrade to ionic 6 is complete

2022-01-27 19:35 UTC, azkyakhan commented
The end slot issue of ion-label is solved in Ionic 6
----
![localhost_8101_home](https://user-images.githubusercontent.com/82817616/151430844-90d9e2c0-59e2-433d-8999-ec07143b8af6.png)

2022-01-27 19:35 UTC, azkyakhan commented
> For extra CSS, there is some written from targeting anchor tag. Please delete that.

Removed sir

2022-01-27 20:57 UTC, dt2patel approved these changes
looks good

2022-01-27 20:57 UTC, merged