Refactored markup and styling  (#1zw388m)
hotwax/commerce-hub pull request #41
Opened 2022-01-28 08:17 UTC by azkyakhan

2022-01-30 23:41 UTC, dt2patel requested changes
changes around logo component

2022-01-30 23:41 UTC, dt2patel commented on src/components/Logo.vue
> +figure > img {
The width of the logo should not be defined in the component but during usage of the component on the login and home page

2022-01-30 23:41 UTC, dt2patel commented on src/views/Home.vue
> +            <ion-card href="">
add route to https://threshold-management.hotwax.io/

2022-01-31 14:43 UTC, azkyakhan commented on src/views/Home.vue
> +            <ion-card href="">
Done

2022-01-31 15:13 UTC, azkyakhan commented on src/components/Logo.vue
> +figure > img {
Width of image inside figure is not getting over rided on home page. I tried using selectors but its not working.

2022-01-31 16:21 UTC, dt2patel commented on src/components/Logo.vue
> +figure > img {
Try setting width of image in figure to 100% and then setting width of logo component in home page

2022-01-31 17:00 UTC, azkyakhan commented on src/components/Logo.vue
> +figure > img {
I tried this but its not working then I tried to set width and margin of figure component on Home page :

![localhost_8100_home (1)](https://user-images.githubusercontent.com/82817616/151838541-a3be3409-5c80-4117-b6da-cc5489d6916a.png)

2022-01-31 17:05 UTC, dt2patel requested changes

2022-01-31 17:05 UTC, dt2patel commented on src/views/Home.vue
> +figure {
indentation

2022-01-31 17:26 UTC, dt2patel approved these changes

2022-01-31 17:26 UTC, azkyakhan commented on src/views/Home.vue
> +figure {
Done sir

2022-01-31 17:26 UTC, merged