Implemented code for static UI of Settings page (#202re98)
hotwax/commerce-hub pull request #58
Opened 2022-02-16 05:40 UTC by azkyakhan

2022-02-16 12:03 UTC, azkyakhan commented
![settings-desktop](https://user-images.githubusercontent.com/82817616/154260893-fb226778-5f44-443e-b18a-bd4c69ffd042.png)

![settings-mobile](https://user-images.githubusercontent.com/82817616/154260913-50bebbc4-3de5-4575-8d4b-eceda556ee92.png)

2022-02-17 13:22 UTC, azkyakhan commented
https://user-images.githubusercontent.com/82817616/154490335-df30b99a-2ccb-49b3-bd00-abc98f6dfd56.mp4

2022-02-18 21:56 UTC, dt2patel requested changes

2022-02-18 21:56 UTC, dt2patel commented on src/views/Settings.vue
> +        <ion-menu-button slot="start" />
Should we remove the menu button too?

2022-02-18 21:56 UTC, dt2patel commented on src/views/Settings.vue
>      <ion-content :fullscreen="true">
Remove full screen. We shouldn't use full screen unless you have to for a UI reason.

2022-02-18 21:56 UTC, dt2patel commented on src/views/Settings.vue
> +      <div>
Use main tag

2022-02-18 21:56 UTC, dt2patel commented on src/views/Settings.vue
> +            <ion-label>{{ $t("OMS") }}</ion-label>
This was functional before so we should keep it functional now too.

2022-02-18 21:56 UTC, dt2patel commented on src/views/Settings.vue
> +            <ion-label>{{ $t("User") }}</ion-label>
User was functional before sho it should remain functional here. User data should stay dynamic.

2022-02-25 04:43 UTC, dt2patel approved these changes

2022-02-25 05:01 UTC, merged

2022-02-25 05:36 UTC, azkyakhan commented on src/views/Settings.vue
> +        <ion-menu-button slot="start" />
I have removed it sir

2022-02-25 05:36 UTC, azkyakhan commented on src/views/Settings.vue
> +      <div>
Replaced div tag with main tag

2022-02-25 05:36 UTC, azkyakhan commented on src/views/Settings.vue
> +            <ion-label>{{ $t("User") }}</ion-label>
Ok sir I have made changes.