Created static code of location management (#202refj)
hotwax/commerce-hub pull request #60
Opened 2022-02-18 10:28 UTC by azkyakhan

2022-02-18 13:18 UTC, azkyakhan commented
![locations-d1](https://user-images.githubusercontent.com/82817616/154689878-9decaaa2-ec5e-41df-8d2f-d857d6de803a.png)

![location-d2](https://user-images.githubusercontent.com/82817616/154689895-846fd407-d57e-4b46-a61d-821c2336861c.png)

![location-m](https://user-images.githubusercontent.com/82817616/154689924-7a5f94a9-fd44-4f2c-8a74-0e142aec12b7.png)

2022-02-18 21:58 UTC, dt2patel approved these changes

2022-02-27 02:26 UTC, dt2patel requested changes

2022-02-27 02:26 UTC, dt2patel commented on src/views/Locations.vue
> +    <ion-content :fullscreen="true">
full screen

2022-02-28 05:32 UTC, azkyakhan commented on src/views/Locations.vue
> +    <ion-content :fullscreen="true">
Removed it sir.

2022-02-28 14:35 UTC, dt2patel approved these changes

2022-02-28 14:35 UTC, merged