#22qhq27
hotwax/commerce-hub pull request #66
Opened 2022-02-25 12:12 UTC by ymaheshwari1

2022-03-04 07:47 UTC, adityasharma7 requested changes

2022-03-04 07:47 UTC, adityasharma7 commented on src/store/modules/order/actions.ts
> -          order.customerName = order.doclist.docs[0].customerPartyName
We will follow
https://github.com/hotwax/commerce-hub/blob/main/src/types/Order.ts#L4
```
customer: {
  name:
  email:
  .....
} 
```

2022-03-04 07:47 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +              <ion-chip id="open-order-created-date-modal" slot="end">
I think this is not action but an id
```suggestion
              <ion-chip id="order-created-date-modal" slot="end">
```

2022-03-04 07:47 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +              <ion-chip id="open-order-created-date-modal" slot="end">
Same applies to other ids

2022-03-04 07:47 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +    orderPromiseDateUpdated(ev: CustomEvent) {
```suggestion
    updateOrderPromiseDate(ev: CustomEvent) {
```
Same applies to other methods

2022-03-04 07:47 UTC, adityasharma7 commented on src/views/FindOrder.vue
> +    await this.store.dispatch('order/getPurchaseOrderIds').then(ids => {
If we are not performing any change to state, action may not be needed. We could directly call service and use the response. WDYT?

2022-03-04 12:31 UTC, ymaheshwari1 commented on src/views/FindOrder.vue
> +              <ion-chip id="open-order-created-date-modal" slot="end">
Sure Sir, will update the ids

2022-03-04 12:44 UTC, ymaheshwari1 commented on src/views/FindOrder.vue
> +    orderPromiseDateUpdated(ev: CustomEvent) {
Sir, changed this logic to use a single method `appliedFiltersUpdated` which in turn calls an action that prepares a query for us. #71

2022-03-07 04:56 UTC, ymaheshwari1 commented on src/views/FindOrder.vue
> +    await this.store.dispatch('order/getPurchaseOrderIds').then(ids => {
Yes Sir, removed the action and directly used the service to get the ids.

2022-03-08 06:47 UTC, ymaheshwari1 commented on src/store/modules/order/actions.ts
> -          order.customerName = order.doclist.docs[0].customerPartyName
Sir, used the same pattern as defined in the order type.

2022-04-05 06:40 UTC, merged