Fixed: Login error when having spaces in the fields ( #20jwqu1 ).
hotwax/commerce-hub pull request #75
Opened 2022-03-08 09:05 UTC by meet-aniket

2022-03-08 09:23 UTC, ymaheshwari1 requested changes

2022-03-08 09:23 UTC, ymaheshwari1 commented on changelogs/unreleased/-20jwqu1.yml
> +title: 'Fixed: Login error when having spaces in the fields (#20jwqu1).'
Remove ticket from the title.

2022-03-08 09:34 UTC, ymaheshwari1 approved these changes

2022-04-06 06:57 UTC, adityasharma7 approved these changes

2022-04-06 06:57 UTC, merged